/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package es.upm.oeg.librairy.api.facade.model.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DocReference extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocReference\",\"namespace\":\"es.upm.oeg.librairy.api.facade.model.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DocReference() {}

  /**
   * All-args constructor.
   */
  public DocReference(java.lang.String id) {
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /** Creates a new DocReference RecordBuilder */
  public static es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder newBuilder() {
    return new es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder();
  }
  
  /** Creates a new DocReference RecordBuilder by copying an existing Builder */
  public static es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder newBuilder(es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder other) {
    return new es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder(other);
  }
  
  /** Creates a new DocReference RecordBuilder by copying an existing DocReference instance */
  public static es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder newBuilder(es.upm.oeg.librairy.api.facade.model.avro.DocReference other) {
    return new es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder(other);
  }
  
  /**
   * RecordBuilder for DocReference instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocReference>
    implements org.apache.avro.data.RecordBuilder<DocReference> {

    private java.lang.String id;

    /** Creates a new Builder */
    private Builder() {
      super(es.upm.oeg.librairy.api.facade.model.avro.DocReference.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DocReference instance */
    private Builder(es.upm.oeg.librairy.api.facade.model.avro.DocReference other) {
            super(es.upm.oeg.librairy.api.facade.model.avro.DocReference.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public es.upm.oeg.librairy.api.facade.model.avro.DocReference.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public DocReference build() {
      try {
        DocReference record = new DocReference();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
