/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package es.upm.oeg.librairy.api.facade.model.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Reference extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Reference\",\"namespace\":\"es.upm.oeg.librairy.api.facade.model.avro\",\"fields\":[{\"name\":\"document\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DocReference\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"default\":null},{\"name\":\"text\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"TextReference\",\"fields\":[{\"name\":\"content\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"model\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private es.upm.oeg.librairy.api.facade.model.avro.DocReference document;
   private es.upm.oeg.librairy.api.facade.model.avro.TextReference text;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Reference() {}

  /**
   * All-args constructor.
   */
  public Reference(es.upm.oeg.librairy.api.facade.model.avro.DocReference document, es.upm.oeg.librairy.api.facade.model.avro.TextReference text) {
    this.document = document;
    this.text = text;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return document;
    case 1: return text;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: document = (es.upm.oeg.librairy.api.facade.model.avro.DocReference)value$; break;
    case 1: text = (es.upm.oeg.librairy.api.facade.model.avro.TextReference)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'document' field.
   */
  public es.upm.oeg.librairy.api.facade.model.avro.DocReference getDocument() {
    return document;
  }

  /**
   * Sets the value of the 'document' field.
   * @param value the value to set.
   */
  public void setDocument(es.upm.oeg.librairy.api.facade.model.avro.DocReference value) {
    this.document = value;
  }

  /**
   * Gets the value of the 'text' field.
   */
  public es.upm.oeg.librairy.api.facade.model.avro.TextReference getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(es.upm.oeg.librairy.api.facade.model.avro.TextReference value) {
    this.text = value;
  }

  /** Creates a new Reference RecordBuilder */
  public static es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder newBuilder() {
    return new es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder();
  }
  
  /** Creates a new Reference RecordBuilder by copying an existing Builder */
  public static es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder newBuilder(es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder other) {
    return new es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder(other);
  }
  
  /** Creates a new Reference RecordBuilder by copying an existing Reference instance */
  public static es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder newBuilder(es.upm.oeg.librairy.api.facade.model.avro.Reference other) {
    return new es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder(other);
  }
  
  /**
   * RecordBuilder for Reference instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Reference>
    implements org.apache.avro.data.RecordBuilder<Reference> {

    private es.upm.oeg.librairy.api.facade.model.avro.DocReference document;
    private es.upm.oeg.librairy.api.facade.model.avro.TextReference text;

    /** Creates a new Builder */
    private Builder() {
      super(es.upm.oeg.librairy.api.facade.model.avro.Reference.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.document)) {
        this.document = data().deepCopy(fields()[0].schema(), other.document);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.text)) {
        this.text = data().deepCopy(fields()[1].schema(), other.text);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Reference instance */
    private Builder(es.upm.oeg.librairy.api.facade.model.avro.Reference other) {
            super(es.upm.oeg.librairy.api.facade.model.avro.Reference.SCHEMA$);
      if (isValidValue(fields()[0], other.document)) {
        this.document = data().deepCopy(fields()[0].schema(), other.document);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.text)) {
        this.text = data().deepCopy(fields()[1].schema(), other.text);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'document' field */
    public es.upm.oeg.librairy.api.facade.model.avro.DocReference getDocument() {
      return document;
    }
    
    /** Sets the value of the 'document' field */
    public es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder setDocument(es.upm.oeg.librairy.api.facade.model.avro.DocReference value) {
      validate(fields()[0], value);
      this.document = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'document' field has been set */
    public boolean hasDocument() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'document' field */
    public es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder clearDocument() {
      document = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'text' field */
    public es.upm.oeg.librairy.api.facade.model.avro.TextReference getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder setText(es.upm.oeg.librairy.api.facade.model.avro.TextReference value) {
      validate(fields()[1], value);
      this.text = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'text' field */
    public es.upm.oeg.librairy.api.facade.model.avro.Reference.Builder clearText() {
      text = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Reference build() {
      try {
        Reference record = new Reference();
        record.document = fieldSetFlags()[0] ? this.document : (es.upm.oeg.librairy.api.facade.model.avro.DocReference) defaultValue(fields()[0]);
        record.text = fieldSetFlags()[1] ? this.text : (es.upm.oeg.librairy.api.facade.model.avro.TextReference) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
