/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package es.upm.oeg.librairy.api.facade.model.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum WriterFormat { 
  SOLR_CORE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WriterFormat\",\"namespace\":\"es.upm.oeg.librairy.api.facade.model.avro\",\"symbols\":[\"SOLR_CORE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
